site_name: 'Web3 User Personas Documentation'
# For production
#site_url: !ENV [DOCS_SITE_URL,"https://shaloo/web3-user-personas"]
site_url: "https://localhost:9090/web3-user-personas"
site_author: shaloo
site_description: Comprehensive analysis of 15 Web3 user personas, covering DeFi, NFTs, gaming, DAOs, and more, built with Material for MkDocs.

# Check for broken links, etc.
strict: true  #For reorg changing it to false

# For canonical/URL ending with a '/' make sure this is true and offline plugin is disabled
use_directory_urls: true

repo_url: https://github.com/shaloo/web3-user-personas
repo_name: shaloo/web3-user-personas
theme:
  name: material
  features:
    - content.code.copy
    - content.tabs
    - navigation.tabs
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.prune
    - navigation.top
    - navigation.sections
    - navigation.footer
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    - header.autohide 
  icon:
    repo: fontawesome/brands/github

nav:
  - Home: 
    - Contents: index.md
    - About: intro/about.md
    - Audience: intro/audience.md
    - Insights: intro/insights.md
    - Get Involved: intro/contribution.md
  - Personas:
    - Overview: personas/index.md
    - DeFi Degen: personas/persona-1-de-fi-degen.md
    - NFT Collector: personas/persona-2-nft-collector.md
    - Crypto Analyst: personas/persona-3-crypto-trader.md
    - Long-term Investor: personas/persona-4-hodler.md
    - Web3 Dev: personas/persona-5-web3-builder.md
    - Crypto Influencer: personas/persona-6-influencer.md
    - Gaming Enthusiast: personas/persona-7-gaming-enthusiast.md
    - DAO Contributor: personas/persona-8-dao-contributor.md
    - Tenderfoot Explorer: personas/persona-9-newcomer.md
    - Institutional Investor: personas/persona-10-institutional-investor.md
    - Meme Culture Participant: personas/persona-11-meme-participant.md
    - Anonymity Advocate: personas/persona-12-privacy-advocate.md
    - AI + Crypto User: personas/persona-13-ai-crypto-user.md
    - Regulation Navigator: personas/persona-14-regulation-navigator.md
    - Sustainability Advocate: personas/persona-15-sustainability-advocate.md
  - Concepts:
    - Personas: concepts/what-personas.md
    - Why Personas: concepts/why-personas.md
    - Web2 vs. Web3: concepts/web2-vs-web3.md
  - References: references.md

markdown_extensions:
  - abbr
  - admonition
  - def_list
  - footnotes
  - toc:
      permalink: true
      title: "On this page"
      toc_depth: 3
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.blocks.caption
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true
  - pymdownx.details
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.snippets:
      auto_append:
        - ./includes/git_info.md
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.arithmatex:   # do not remove, used in ADKG section
      generic: true
  - tables

plugins:
  - offline:
      enabled: !ENV [OFFLINE, false] #should not be true for production build
  - macros:
      include_dir: ./includes
  - search
  - alias
  - open-in-new-tab
  - git-revision-date-localized:
      enabled: true
      type: date
  - glightbox:
      touchNavigation: true
      loop: false
      effect: zoom
      slide_effect: fade
      width: 100%
      height: auto
      zoomable: true
      draggable: true
      skip_classes:
        - custom-screenshots-noeffects
      auto_caption: true
      caption_position: bottom  

extra_css:
  - css/extra.css

extra_javascript:
  - javascripts/extra.js   # Do not remove, required for ADKG formulae
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

extra:
  web3_personas:
    img_dir: /web3-user-personas/img
    img_png: webp

  # Remove made with Material notice in the footer   
  generator: false

  social:
    - icon: material/home
      link: https://shaloo.github.io/web3-user-personas
    - icon: fontawesome/brands/x-twitter
      link: https://twitter.com/shalooshalini
    #- icon: fontawesome/brands/telegram
    #  link: https://t.me/ArcanaNetwork
    #- icon: fontawesome/brands/discord
    #  link: https://discord.gg/9vrxze3JRR
    - icon: material/github
      link: https://github.com/shaloo/web3-user-personas/discussions
    #- icon: material/book
      #link: https://www.webfx.com/tools/read-able/referer.php
    - icon: material/robot
      link: /llms.txt